development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redis://rediscloud:FdE4ECt0H1Zml8SJjhKX91nkR56gdi1S@redis-11592.c1.eu-west-1-3.ec2.cloud.redislabs.com:11592") { "redis://localhost:6379/1" } %>
  channel_prefix: slack_clone_production
